### PR TITLE
Fix 4848

### PR DESCRIPTION
**Pull request by partouf**
Aiming to fix https://github.com/compiler-explorer/compiler-explorer/issues/4848

Issue is: function starts with library file

Discussed before elsewhere, but to really fix this we must:
- Move the library filter to a post-process step
- Only eliminate the function that has no usercode at all, otherwise leave it

### CODE REVIEW

**Comment by OfekShilon** [comment]
Not sure what the fix was supposed to do. The problem (the `rdtsc` drop) persists even when checking off the library filter.

**Comment by partouf** [comment]
> * Only eliminate the function that has no usercode at all, otherwise leave it

Correct, but the part that wasn't implemented here was the 2nd bulletpoint `Only eliminate the function that has no usercode at all, otherwise leave it`

**Comment by partouf** [comment]
(And it had a bug where libcode was sometimes always filtered it without looking at the filter setting)

**Comment by partouf** [comment]
But am extremely fuzzy on the details, i shouldve continued this pr when i understood what was going on

**Pull request merged**
